# Generated by Django 5.0.6 on 2024-05-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ticket_payment_status_alter_ticket_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettemplate',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
