# Generated by Django 5.0.6 on 2024-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tickettemplate_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
