# Generated by Django 5.0.6 on 2024-06-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_passenger_id_alter_wallet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='payment_status',
        ),
    ]
