# Generated by Django 5.0.6 on 2024-06-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_ticket_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='purchase_date',
        ),
    ]
